// flow-typed signature: ef4c831bcba9a0808b7d2f5371dc4a09
// flow-typed version: <<STUB>>/material-ui-pickers_v^1.0.0-rc.9/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui-pickers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui-pickers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui-pickers/_helpers/date-utils' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_helpers/time-utils' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/BasePicker' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/DateTextField' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/MaskedInput' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/ModalDialog' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/PickerToolbar' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/ToolbarButton' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/WithUtils' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/constants/clock-types' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/constants/date-picker-view' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/constants/prop-types' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/Calendar' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/CalendarHeader' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/DatePicker' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/DatePickerWrapper' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/Day' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/DayWrapper' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/index' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/SlideTransition' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/Year' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/YearSelection' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/DateTimePicker' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/DateTimePickerHeader' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/DateTimePickerTabs' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/DateTimePickerView' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/DateTimePickerWrapper' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/index' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/dist/material-ui-pickers.cjs' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/dist/material-ui-pickers.esm' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/dist/material-ui-pickers.umd' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/dist/material-ui-pickers.umd.min' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/index.es' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/Clock' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/ClockNumber' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/ClockNumbers' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/ClockPointer' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/index' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/TimePicker' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/TimePickerView' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/TimePickerWrapper' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/utils/date-fns-utils' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/utils/luxon-utils' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/utils/moment-utils' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/utils/MuiPickersUtilsProvider' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/wrappers/ModalWrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui-pickers/_helpers/date-utils.js' {
  declare module.exports: $Exports<'material-ui-pickers/_helpers/date-utils'>;
}
declare module 'material-ui-pickers/_helpers/time-utils.js' {
  declare module.exports: $Exports<'material-ui-pickers/_helpers/time-utils'>;
}
declare module 'material-ui-pickers/_shared/BasePicker.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/BasePicker'>;
}
declare module 'material-ui-pickers/_shared/DateTextField.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/DateTextField'>;
}
declare module 'material-ui-pickers/_shared/MaskedInput.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/MaskedInput'>;
}
declare module 'material-ui-pickers/_shared/ModalDialog.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/ModalDialog'>;
}
declare module 'material-ui-pickers/_shared/PickerToolbar.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/PickerToolbar'>;
}
declare module 'material-ui-pickers/_shared/ToolbarButton.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/ToolbarButton'>;
}
declare module 'material-ui-pickers/_shared/WithUtils.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/WithUtils'>;
}
declare module 'material-ui-pickers/constants/clock-types.js' {
  declare module.exports: $Exports<'material-ui-pickers/constants/clock-types'>;
}
declare module 'material-ui-pickers/constants/date-picker-view.js' {
  declare module.exports: $Exports<'material-ui-pickers/constants/date-picker-view'>;
}
declare module 'material-ui-pickers/constants/prop-types.js' {
  declare module.exports: $Exports<'material-ui-pickers/constants/prop-types'>;
}
declare module 'material-ui-pickers/DatePicker/Calendar.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/Calendar'>;
}
declare module 'material-ui-pickers/DatePicker/CalendarHeader.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/CalendarHeader'>;
}
declare module 'material-ui-pickers/DatePicker/DatePicker.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/DatePicker'>;
}
declare module 'material-ui-pickers/DatePicker/DatePickerWrapper.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/DatePickerWrapper'>;
}
declare module 'material-ui-pickers/DatePicker/Day.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/Day'>;
}
declare module 'material-ui-pickers/DatePicker/DayWrapper.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/DayWrapper'>;
}
declare module 'material-ui-pickers/DatePicker/index.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/index'>;
}
declare module 'material-ui-pickers/DatePicker/SlideTransition.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/SlideTransition'>;
}
declare module 'material-ui-pickers/DatePicker/Year.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/Year'>;
}
declare module 'material-ui-pickers/DatePicker/YearSelection.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/YearSelection'>;
}
declare module 'material-ui-pickers/DateTimePicker/DateTimePicker.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/DateTimePicker'>;
}
declare module 'material-ui-pickers/DateTimePicker/DateTimePickerHeader.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/DateTimePickerHeader'>;
}
declare module 'material-ui-pickers/DateTimePicker/DateTimePickerTabs.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/DateTimePickerTabs'>;
}
declare module 'material-ui-pickers/DateTimePicker/DateTimePickerView.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/DateTimePickerView'>;
}
declare module 'material-ui-pickers/DateTimePicker/DateTimePickerWrapper.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/DateTimePickerWrapper'>;
}
declare module 'material-ui-pickers/DateTimePicker/index.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/index'>;
}
declare module 'material-ui-pickers/dist/material-ui-pickers.cjs.js' {
  declare module.exports: $Exports<'material-ui-pickers/dist/material-ui-pickers.cjs'>;
}
declare module 'material-ui-pickers/dist/material-ui-pickers.esm.js' {
  declare module.exports: $Exports<'material-ui-pickers/dist/material-ui-pickers.esm'>;
}
declare module 'material-ui-pickers/dist/material-ui-pickers.umd.js' {
  declare module.exports: $Exports<'material-ui-pickers/dist/material-ui-pickers.umd'>;
}
declare module 'material-ui-pickers/dist/material-ui-pickers.umd.min.js' {
  declare module.exports: $Exports<'material-ui-pickers/dist/material-ui-pickers.umd.min'>;
}
declare module 'material-ui-pickers/index.es.js' {
  declare module.exports: $Exports<'material-ui-pickers/index.es'>;
}
declare module 'material-ui-pickers/index' {
  declare module.exports: $Exports<'material-ui-pickers'>;
}
declare module 'material-ui-pickers/index.js' {
  declare module.exports: $Exports<'material-ui-pickers'>;
}
declare module 'material-ui-pickers/TimePicker/Clock.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/Clock'>;
}
declare module 'material-ui-pickers/TimePicker/ClockNumber.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/ClockNumber'>;
}
declare module 'material-ui-pickers/TimePicker/ClockNumbers.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/ClockNumbers'>;
}
declare module 'material-ui-pickers/TimePicker/ClockPointer.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/ClockPointer'>;
}
declare module 'material-ui-pickers/TimePicker/index.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/index'>;
}
declare module 'material-ui-pickers/TimePicker/TimePicker.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/TimePicker'>;
}
declare module 'material-ui-pickers/TimePicker/TimePickerView.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/TimePickerView'>;
}
declare module 'material-ui-pickers/TimePicker/TimePickerWrapper.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/TimePickerWrapper'>;
}
declare module 'material-ui-pickers/utils/date-fns-utils.js' {
  declare module.exports: $Exports<'material-ui-pickers/utils/date-fns-utils'>;
}
declare module 'material-ui-pickers/utils/luxon-utils.js' {
  declare module.exports: $Exports<'material-ui-pickers/utils/luxon-utils'>;
}
declare module 'material-ui-pickers/utils/moment-utils.js' {
  declare module.exports: $Exports<'material-ui-pickers/utils/moment-utils'>;
}
declare module 'material-ui-pickers/utils/MuiPickersUtilsProvider.js' {
  declare module.exports: $Exports<'material-ui-pickers/utils/MuiPickersUtilsProvider'>;
}
declare module 'material-ui-pickers/wrappers/ModalWrapper.js' {
  declare module.exports: $Exports<'material-ui-pickers/wrappers/ModalWrapper'>;
}
