// flow-typed signature: e2ea9350761fa2a8d3260ac67a30324e
// flow-typed version: <<STUB>>/normalize.css_v^8.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
