// flow-typed signature: 345506e0d1ef0084ec46ce8ecc57eefb
// flow-typed version: <<STUB>>/react-validation_v^3.0.7/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-validation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-validation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-validation/build/button' {
  declare module.exports: any;
}

declare module 'react-validation/build/form' {
  declare module.exports: any;
}

declare module 'react-validation/build/input' {
  declare module.exports: any;
}

declare module 'react-validation/build/main' {
  declare module.exports: any;
}

declare module 'react-validation/build/select' {
  declare module.exports: any;
}

declare module 'react-validation/build/textarea' {
  declare module.exports: any;
}

declare module 'react-validation/src/components/base/index' {
  declare module.exports: any;
}

declare module 'react-validation/src/components/button/index' {
  declare module.exports: any;
}

declare module 'react-validation/src/components/form/index' {
  declare module.exports: any;
}

declare module 'react-validation/src/components/input/index' {
  declare module.exports: any;
}

declare module 'react-validation/src/components/select/index' {
  declare module.exports: any;
}

declare module 'react-validation/src/components/textarea/index' {
  declare module.exports: any;
}

declare module 'react-validation/src/hocs/button/index' {
  declare module.exports: any;
}

declare module 'react-validation/src/hocs/control/index' {
  declare module.exports: any;
}

declare module 'react-validation/src/hocs/form/index' {
  declare module.exports: any;
}

declare module 'react-validation/src/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-validation/build/button.js' {
  declare module.exports: $Exports<'react-validation/build/button'>;
}
declare module 'react-validation/build/form.js' {
  declare module.exports: $Exports<'react-validation/build/form'>;
}
declare module 'react-validation/build/input.js' {
  declare module.exports: $Exports<'react-validation/build/input'>;
}
declare module 'react-validation/build/main.js' {
  declare module.exports: $Exports<'react-validation/build/main'>;
}
declare module 'react-validation/build/select.js' {
  declare module.exports: $Exports<'react-validation/build/select'>;
}
declare module 'react-validation/build/textarea.js' {
  declare module.exports: $Exports<'react-validation/build/textarea'>;
}
declare module 'react-validation/src/components/base/index.js' {
  declare module.exports: $Exports<'react-validation/src/components/base/index'>;
}
declare module 'react-validation/src/components/button/index.js' {
  declare module.exports: $Exports<'react-validation/src/components/button/index'>;
}
declare module 'react-validation/src/components/form/index.js' {
  declare module.exports: $Exports<'react-validation/src/components/form/index'>;
}
declare module 'react-validation/src/components/input/index.js' {
  declare module.exports: $Exports<'react-validation/src/components/input/index'>;
}
declare module 'react-validation/src/components/select/index.js' {
  declare module.exports: $Exports<'react-validation/src/components/select/index'>;
}
declare module 'react-validation/src/components/textarea/index.js' {
  declare module.exports: $Exports<'react-validation/src/components/textarea/index'>;
}
declare module 'react-validation/src/hocs/button/index.js' {
  declare module.exports: $Exports<'react-validation/src/hocs/button/index'>;
}
declare module 'react-validation/src/hocs/control/index.js' {
  declare module.exports: $Exports<'react-validation/src/hocs/control/index'>;
}
declare module 'react-validation/src/hocs/form/index.js' {
  declare module.exports: $Exports<'react-validation/src/hocs/form/index'>;
}
declare module 'react-validation/src/main.js' {
  declare module.exports: $Exports<'react-validation/src/main'>;
}
