// flow-typed signature: 9760cb69e867f38dc1785e811d0d42d6
// flow-typed version: <<STUB>>/reduce-reducers_v^0.4.3/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reduce-reducers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reduce-reducers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reduce-reducers/es/index' {
  declare module.exports: any;
}

declare module 'reduce-reducers/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reduce-reducers/es/index.js' {
  declare module.exports: $Exports<'reduce-reducers/es/index'>;
}
declare module 'reduce-reducers/lib/index.js' {
  declare module.exports: $Exports<'reduce-reducers/lib/index'>;
}
