// flow-typed signature: c14a400d314517438face9c74609a274
// flow-typed version: <<STUB>>/@integreat-app/shared_v^0.0.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@integreat-app/shared'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@integreat-app/shared' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@integreat-app/shared/index' {
  declare module.exports: $Exports<'@integreat-app/shared'>;
}
declare module '@integreat-app/shared/index.js' {
  declare module.exports: $Exports<'@integreat-app/shared'>;
}
